### ISSUE TITLE
Level three header formatting not being applied

### ISSUE THREAD

**Issue by joelnitta** [kazuyanagimoto/quarto-awesomecv-typst#2]
In the `qmd` file, if I have this:

````
## Skills

```{=typst}
=== Level 3 header
```

### Should be level three
````

The output looks like this:

![image](https://github.com/user-attachments/assets/cec84623-71a1-45ee-ad1e-a0f562f9065a)

**Comment by kazuyanagimoto** [comment]
It is related to a tricky thing in Quarto. When Quarto converts `.qmd` file to `.typ`, the heading level will be adjusted automatically. For example,

````md
---
author:
  firstname: Albert
  lastname: Einstein
format:
  awesomecv-typst:
    keep-typ: true
---

## Level 2

### Level 3

#### Level 4

````

will be converted to

```typ
= Level 2
<level-2>
== Level 3
<level-3>
=== Level 4
<level-4>
```

The top level of the heading will be assigned to the heading level 1. While this is not intuitive, the "Skills" section in your example is actually the level 1 heading in Typst. You can use the heading level 3 by
1. Starts from the heading level 1 in Quarto.
1. Starts from the heading level 2 in Quarto and use `####` as the level 3 headings

**Comment by joelnitta** [comment]
Got it, thanks for the explanation.
